// This file is auto-generated by @hey-api/openapi-ts

export type Error = {
    success?: boolean;
    error?: string;
};

export type Matrix = {
    id?: number;
    name?: string;
    description?: string;
    projectId?: number;
    isSubMatrix?: boolean;
    config?: {
        [key: string]: unknown;
    };
    status?: 'active' | 'inactive';
};

export type status = 'active' | 'inactive';

export type Project = {
    id?: number;
    name?: string;
    description?: string;
};

export type Success = {
    success?: boolean;
    data?: {
        [key: string]: unknown;
    };
};

export type Trigger = {
    id?: number;
    nodeId?: number;
    type?: string;
    name?: string;
    config?: {
        [key: string]: unknown;
    };
    status?: 'active' | 'inactive';
    lastTriggered?: string;
};

export type PostApiExecuteMatrixByIdData = {
    body: {
        /**
         * Input data for the matrix execution
         */
        input?: {
            [key: string]: unknown;
        };
    };
    path: {
        /**
         * Matrix ID
         */
        id: number;
    };
};

export type PostApiExecuteMatrixByIdResponse = ({
    success?: boolean;
    message?: string;
    matrixId?: string;
    input?: {
        [key: string]: unknown;
    };
});

export type PostApiExecuteMatrixByIdError = (unknown);

export type GetApiMatrixResponse = ({
    status?: string;
    data?: Array<Matrix>;
});

export type GetApiMatrixError = unknown;

export type PostApiMatrixData = {
    body: {
        name: string;
        description?: string;
        projectId: number;
        isSubMatrix?: boolean;
        config?: {
            [key: string]: unknown;
        };
    };
};

export type PostApiMatrixResponse = (unknown);

export type PostApiMatrixError = unknown;

export type GetApiMatrixByIdData = {
    path: {
        id: number;
    };
};

export type GetApiMatrixByIdResponse = (unknown);

export type GetApiMatrixByIdError = (unknown);

export type PutApiMatrixByIdData = {
    body: Matrix;
    path: {
        id: number;
    };
};

export type PutApiMatrixByIdResponse = (unknown);

export type PutApiMatrixByIdError = unknown;

export type DeleteApiMatrixByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiMatrixByIdResponse = (unknown);

export type DeleteApiMatrixByIdError = unknown;

export type GetApiMatrixByIdNodesData = {
    path: {
        id: number;
    };
};

export type GetApiMatrixByIdNodesResponse = (unknown);

export type GetApiMatrixByIdNodesError = unknown;

export type GetApiMatrixByIdConnectionsData = {
    path: {
        id: number;
    };
};

export type GetApiMatrixByIdConnectionsResponse = (unknown);

export type GetApiMatrixByIdConnectionsError = unknown;

export type GetApiNodeTypeResponse = ({
    success?: boolean;
    data?: Array<(string)>;
});

export type GetApiNodeTypeError = (unknown);

export type GetApiProjectResponse = ({
    status?: string;
    data?: Array<Project>;
});

export type GetApiProjectError = unknown;

export type PostApiProjectData = {
    body: {
        name: string;
        description?: string;
    };
};

export type PostApiProjectResponse = (unknown);

export type PostApiProjectError = unknown;

export type GetApiProjectByIdData = {
    path: {
        id: number;
    };
};

export type GetApiProjectByIdResponse = (unknown);

export type GetApiProjectByIdError = unknown;

export type PutApiProjectByIdData = {
    body: Project;
    path: {
        id: number;
    };
};

export type PutApiProjectByIdResponse = (unknown);

export type PutApiProjectByIdError = unknown;

export type DeleteApiProjectByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiProjectByIdResponse = (unknown);

export type DeleteApiProjectByIdError = unknown;

export type GetApiTriggerResponse = (unknown);

export type GetApiTriggerError = unknown;

export type PostApiTriggerData = {
    body: {
        nodeId: number;
        type: string;
        name: string;
        config?: {
            [key: string]: unknown;
        };
    };
};

export type PostApiTriggerResponse = (unknown);

export type PostApiTriggerError = unknown;

export type GetApiTriggerByIdData = {
    path: {
        id: number;
    };
};

export type GetApiTriggerByIdResponse = (unknown);

export type GetApiTriggerByIdError = unknown;

export type PutApiTriggerByIdData = {
    body: {
        name?: string;
        config?: {
            [key: string]: unknown;
        };
        status?: 'active' | 'inactive';
    };
    path: {
        id: number;
    };
};

export type PutApiTriggerByIdResponse = (unknown);

export type PutApiTriggerByIdError = unknown;

export type DeleteApiTriggerByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiTriggerByIdResponse = (unknown);

export type DeleteApiTriggerByIdError = unknown;